-- MySQL Script generated by MySQL Workbench
-- Wed 08 Aug 2018 11:32:31 PM MDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema refactoring_stats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema refactoring_stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refactoring_stats` DEFAULT CHARACTER SET utf8 ;
USE `refactoring_stats` ;

-- -----------------------------------------------------
-- Table `refactoring_stats`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2000) NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`merge_commit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`merge_commit` (
  `commit_hash` CHAR(40) NOT NULL,
  `project_id` INT NOT NULL,
  `is_conflicting` TINYINT(1) NULL,
  PRIMARY KEY (`commit_hash`, `project_id`),
  INDEX `fk_merge_commit_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_merge_commit_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `refactoring_stats`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`merge_parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`merge_parent` (
  `commit_hash` CHAR(40) NOT NULL,
  `merge_commit` CHAR(40) NOT NULL,
  INDEX `fk_merge_child_merge_commit1_idx` (`merge_commit` ASC),
  PRIMARY KEY (`merge_commit`, `commit_hash`),
  CONSTRAINT `fk_merge_child_merge_commit1`
    FOREIGN KEY (`merge_commit`)
    REFERENCES `refactoring_stats`.`merge_commit` (`commit_hash`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`refactoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`refactoring` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commit_hash` CHAR(40) NOT NULL,
  `refactoring_type` VARCHAR(100) NULL,
  `refactoring_detail` VARCHAR(1000) NULL,
  `merge_commit` CHAR(40) NOT NULL,
  `merge_parent` CHAR(40) NOT NULL,
  PRIMARY KEY (`id`, `merge_commit`, `merge_parent`),
  CONSTRAINT `fk_refactoring_commit_merge_parent1`
    FOREIGN KEY (`merge_commit` , `merge_parent`)
    REFERENCES `refactoring_stats`.`merge_parent` (`merge_commit` , `commit_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`conflicting_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`conflicting_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `merge_commit` CHAR(40) NOT NULL,
  `path` VARCHAR(1000) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  INDEX `fk_conflicting_file_1_idx` (`merge_commit` ASC),
  PRIMARY KEY (`id`, `merge_commit`),
  CONSTRAINT `fk_conflicting_file_1`
    FOREIGN KEY (`merge_commit`)
    REFERENCES `refactoring_stats`.`merge_commit` (`commit_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`conflicting_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`conflicting_region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_line` INT NOT NULL,
  `length` INT NOT NULL,
  `merge_commit` CHAR(40) NOT NULL,
  `merge_parent` CHAR(40) NOT NULL,
  `conflicting_file_id` INT NOT NULL,
  PRIMARY KEY (`id`, `conflicting_file_id`, `merge_parent`, `merge_commit`),
  INDEX `fk_conflicting_region_merge_parent1_idx` (`merge_commit` ASC, `merge_parent` ASC),
  INDEX `fk_conflicting_region_conflicting_file1_idx` (`conflicting_file_id` ASC, `merge_commit` ASC),
  CONSTRAINT `fk_conflicting_region_merge_parent1`
    FOREIGN KEY (`merge_commit` , `merge_parent`)
    REFERENCES `refactoring_stats`.`merge_parent` (`merge_commit` , `commit_hash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conflicting_region_conflicting_file1`
    FOREIGN KEY (`conflicting_file_id` , `merge_commit`)
    REFERENCES `refactoring_stats`.`conflicting_file` (`id` , `merge_commit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`refactoring_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`refactoring_region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` CHAR(1) NOT NULL,
  `path` VARCHAR(1000) NOT NULL,
  `start_line` INT NOT NULL,
  `length` INT NOT NULL,
  `refactoring_id` INT NOT NULL,
  PRIMARY KEY (`id`, `refactoring_id`),
  CONSTRAINT `fk_refactoring_region_refactoring1`
    FOREIGN KEY (`refactoring_id`)
    REFERENCES `refactoring_stats`.`refactoring` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refactoring_stats`.`conflicting_region_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refactoring_stats`.`conflicting_region_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commit_hash` CHAR(40) NOT NULL,
  `old_start_line` INT NOT NULL,
  `old_length` INT NOT NULL,
  `new_start_line` INT NOT NULL,
  `new_length` INT NOT NULL,
  `conflicting_region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `conflicting_region_id`),
  INDEX `fk_conflicting_region_history_conflicting_region1_idx` (`conflicting_region_id` ASC),
  CONSTRAINT `fk_conflicting_region_history_conflicting_region1`
    FOREIGN KEY (`conflicting_region_id`)
    REFERENCES `refactoring_stats`.`conflicting_region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `refactoring_stats` ;

-- -----------------------------------------------------
-- function commit_url
-- -----------------------------------------------------

DELIMITER $$
USE `refactoring_stats`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `commit_url`(commit_hash char(40), project_url varchar(1000)) RETURNS varchar(1000) CHARSET utf8
BEGIN
RETURN CONCAT("[" , substring(commit_hash, 1, 7) , "](", project_url, "/commit/", commit_hash, ")");
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
